SELECT
PERPETUAL_ID,
NON_ADJUSTED_VOLUME,
NON_ADJUSTED_PRICE,
NON_ADJUSTED_VOLUME*NON_ADJUSTED_PRICE as VOLUME_USD_UNADJUSTED,
TAKER,
TAKER_ORDER_ID,
MAKER,
MAKER_ORDER_ID

FROM (
SELECT
PERPETUAL_ID,
ABS(MAKER_PERPETUAL_QUANTUMS_DELTA_BASE_QUANTUMS) AS NON_ADJUSTED_VOLUME,
ABS((TAKER_QUOTE_BALANCE_DELTA_QUOTE_QUANTUMS+TAKER_ORDER_FEE_QUOTE_QUANTUMS)/TAKER_PERPETUAL_QUANTUMS_DELTA_BASE_QUANTUMS) AS NON_ADJUSTED_PRICE,
TAKER,
TAKER_ORDER_ID,
MAKER,
MAKER_ORDER_ID
FROM 
  `numia-data.dydx_mainnet.dydx_match`  A
WHERE block_height = 22651850  -- Replace with any block
) A 
order by maker
